import { VizceralGraph } from './types';
import { utils } from './utils';

export const backendClient = {
  getVizsceralGraphAsync: async (): Promise<VizceralGraph> => {
    const graph = utils.getGraphFromMeshNodes(response.meshNodes as any);
    return graph;
  },
};

const response = {
  meshNodes: [
    {
      stats: {
        version_string: '',
        startOfCurrentUTCDay_string: '0001-01-01T00:00:00Z',
        rendezvous_string: '',
        pubSubTopic_string: '',
        numPinnedOrders_number: 0,
        numPeers_number: 0,
        numOrders_number: 0,
        numOrdersIncludingRemoved_number: 0,
        myPeerID: '',
        msg: '',
        maxExpirationTime_string: '',
        level: '',
        latestBlock_rpc_LatestBlock: {
          hash: '',
          number: 0,
        },
        ethereumChainID_number: 0,
        ethRPCRequestsSentInCurrentUTCDay_number: 0,
        ethRPCRateLimitExpiredRequests_number: 0,
        '@timestamp': '0001-01-01T00:00:00Z',
      },
      peers: {
        '16Uiu2HAkxDnnjyKGgojt6ad5j59xT4kAaoM2km1YHtWrDiYQvG78': {},
        '16Uiu2HAm64hsnKPxoVYv7M84z42Ra7gpBK1zY4rEddg29cSqvPoy': {},
      },
      meshVersion: '',
      ip: '',
      multiAddress: '/ip4/68.111.231.38/tcp/56721',
      peerId: '16Uiu2HAkzu43TqfLEYiUtQegwb3n2dsdbUWUXkqgaABM8riYVsv8',
      name: '16Uiu2HAkzu43TqfLEYiUtQegwb3n2dsdbUWUXkqgaABM8riYVsv8',
    },
    {
      stats: {
        version_string: '',
        startOfCurrentUTCDay_string: '0001-01-01T00:00:00Z',
        rendezvous_string: '',
        pubSubTopic_string: '',
        numPinnedOrders_number: 0,
        numPeers_number: 0,
        numOrders_number: 0,
        numOrdersIncludingRemoved_number: 0,
        myPeerID: '',
        msg: '',
        maxExpirationTime_string: '',
        level: '',
        latestBlock_rpc_LatestBlock: {
          hash: '',
          number: 0,
        },
        ethereumChainID_number: 0,
        ethRPCRequestsSentInCurrentUTCDay_number: 0,
        ethRPCRateLimitExpiredRequests_number: 0,
        '@timestamp': '0001-01-01T00:00:00Z',
      },
      peers: {
        '16Uiu2HAkzu43TqfLEYiUtQegwb3n2dsdbUWUXkqgaABM8riYVsv8': {},
        '16Uiu2HAm64hsnKPxoVYv7M84z42Ra7gpBK1zY4rEddg29cSqvPoy': {},
      },
      meshVersion: '',
      ip: '',
      multiAddress: '/ip4/92.251.59.182/tcp/59538',
      peerId: '16Uiu2HAkxDnnjyKGgojt6ad5j59xT4kAaoM2km1YHtWrDiYQvG78',
      name: '16Uiu2HAkxDnnjyKGgojt6ad5j59xT4kAaoM2km1YHtWrDiYQvG78',
    },
    {
      stats: {
        version_string: '',
        startOfCurrentUTCDay_string: '0001-01-01T00:00:00Z',
        rendezvous_string: '',
        pubSubTopic_string: '',
        numPinnedOrders_number: 0,
        numPeers_number: 0,
        numOrders_number: 0,
        numOrdersIncludingRemoved_number: 0,
        myPeerID: '',
        msg: '',
        maxExpirationTime_string: '',
        level: '',
        latestBlock_rpc_LatestBlock: {
          hash: '',
          number: 0,
        },
        ethereumChainID_number: 0,
        ethRPCRequestsSentInCurrentUTCDay_number: 0,
        ethRPCRateLimitExpiredRequests_number: 0,
        '@timestamp': '0001-01-01T00:00:00Z',
      },
      peers: null,
      meshVersion: '',
      ip: '',
      multiAddress: '/ip4/73.70.162.200/tcp/57601',
      peerId: '16Uiu2HAm64hsnKPxoVYv7M84z42Ra7gpBK1zY4rEddg29cSqvPoy',
      name: '16Uiu2HAm64hsnKPxoVYv7M84z42Ra7gpBK1zY4rEddg29cSqvPoy',
    },
    {
      stats: {
        version_string: '',
        startOfCurrentUTCDay_string: '0001-01-01T00:00:00Z',
        rendezvous_string: '',
        pubSubTopic_string: '',
        numPinnedOrders_number: 0,
        numPeers_number: 0,
        numOrders_number: 0,
        numOrdersIncludingRemoved_number: 0,
        myPeerID: '',
        msg: '',
        maxExpirationTime_string: '',
        level: '',
        latestBlock_rpc_LatestBlock: {
          hash: '',
          number: 0,
        },
        ethereumChainID_number: 0,
        ethRPCRequestsSentInCurrentUTCDay_number: 0,
        ethRPCRateLimitExpiredRequests_number: 0,
        '@timestamp': '0001-01-01T00:00:00Z',
      },
      peers: null,
      meshVersion: '',
      ip: '',
      multiAddress: '/ip4/73.70.162.200/tcp/65495',
      peerId: '16Uiu2HAmA34Kt4PoA4TKDnnRgAdAT7KhEqiR8iFQXXBmTh2CtoF2',
      name: '16Uiu2HAmA34Kt4PoA4TKDnnRgAdAT7KhEqiR8iFQXXBmTh2CtoF2',
    },
    {
      stats: {
        version_string: '',
        startOfCurrentUTCDay_string: '0001-01-01T00:00:00Z',
        rendezvous_string: '',
        pubSubTopic_string: '',
        numPinnedOrders_number: 0,
        numPeers_number: 0,
        numOrders_number: 0,
        numOrdersIncludingRemoved_number: 0,
        myPeerID: '',
        msg: '',
        maxExpirationTime_string: '',
        level: '',
        latestBlock_rpc_LatestBlock: {
          hash: '',
          number: 0,
        },
        ethereumChainID_number: 0,
        ethRPCRequestsSentInCurrentUTCDay_number: 0,
        ethRPCRateLimitExpiredRequests_number: 0,
        '@timestamp': '0001-01-01T00:00:00Z',
      },
      peers: null,
      meshVersion: '',
      ip: '',
      multiAddress: '/ip4/73.70.162.200/tcp/37988',
      peerId: '16Uiu2HAmPA1hG6HJLmdZ9h6npqyU3Hck63WbfUGvz8eoFfjyZQJC',
      name: '16Uiu2HAmPA1hG6HJLmdZ9h6npqyU3Hck63WbfUGvz8eoFfjyZQJC',
    },
    {
      stats: {
        version_string: '7.1.1-beta-0xv3',
        startOfCurrentUTCDay_string: '2019-12-04T00:00:00Z',
        rendezvous_string: '/0x-mesh/network/1/version/2',
        pubSubTopic_string: '/0x-orders/network/1/version/2',
        numPinnedOrders_number: 277,
        numPeers_number: 65,
        numOrders_number: 84,
        numOrdersIncludingRemoved_number: 311,
        myPeerID: '16Uiu2HAmQPnxNfshgDD7FRqK5HvD12SCL1oDA8y3dUh6cwt75C6u',
        msg: 'current stats',
        maxExpirationTime_string: '115792089237316195423570985008687907853269984665640564039457584007913129639935',
        level: 'info',
        latestBlock_rpc_LatestBlock: {
          hash: '0xf01e7929d0e4dcda68ae868939e23219dd884c7af5a7a8cf00aa449c666dd8c5',
          number: 9051873,
        },
        ethereumChainID_number: 1,
        ethRPCRequestsSentInCurrentUTCDay_number: 68073,
        ethRPCRateLimitExpiredRequests_number: 0,
        '@timestamp': '2019-12-04T23:29:23Z',
      },
      peers: null,
      meshVersion: '',
      ip: '',
      multiAddress: '/ip4/3.84.127.243/tcp/34026/ws',
      peerId: '16Uiu2HAmQPnxNfshgDD7FRqK5HvD12SCL1oDA8y3dUh6cwt75C6u',
      name: '16Uiu2HAmQPnxNfshgDD7FRqK5HvD12SCL1oDA8y3dUh6cwt75C6u',
    },
    {
      stats: {
        version_string: '',
        startOfCurrentUTCDay_string: '0001-01-01T00:00:00Z',
        rendezvous_string: '',
        pubSubTopic_string: '',
        numPinnedOrders_number: 0,
        numPeers_number: 0,
        numOrders_number: 0,
        numOrdersIncludingRemoved_number: 0,
        myPeerID: '',
        msg: '',
        maxExpirationTime_string: '',
        level: '',
        latestBlock_rpc_LatestBlock: {
          hash: '',
          number: 0,
        },
        ethereumChainID_number: 0,
        ethRPCRequestsSentInCurrentUTCDay_number: 0,
        ethRPCRateLimitExpiredRequests_number: 0,
        '@timestamp': '0001-01-01T00:00:00Z',
      },
      peers: null,
      meshVersion: '',
      ip: '',
      multiAddress: '/ip4/73.70.162.200/tcp/58195',
      peerId: '16Uiu2HAmBQBShVZpSJNjvDzKLEs9LCVcz26kd9TNsjqWU9SQW6Jr',
      name: '16Uiu2HAmBQBShVZpSJNjvDzKLEs9LCVcz26kd9TNsjqWU9SQW6Jr',
    },
    {
      stats: {
        version_string: '',
        startOfCurrentUTCDay_string: '0001-01-01T00:00:00Z',
        rendezvous_string: '',
        pubSubTopic_string: '',
        numPinnedOrders_number: 0,
        numPeers_number: 0,
        numOrders_number: 0,
        numOrdersIncludingRemoved_number: 0,
        myPeerID: '',
        msg: '',
        maxExpirationTime_string: '',
        level: '',
        latestBlock_rpc_LatestBlock: {
          hash: '',
          number: 0,
        },
        ethereumChainID_number: 0,
        ethRPCRequestsSentInCurrentUTCDay_number: 0,
        ethRPCRateLimitExpiredRequests_number: 0,
        '@timestamp': '0001-01-01T00:00:00Z',
      },
      peers: null,
      meshVersion: '',
      ip: '',
      multiAddress: '/ip4/52.91.1.144/tcp/60558',
      peerId: '16Uiu2HAkzn4wcaftAcsybKsE3GEboZCYLb7mpRBmPshpiwazAW3m',
      name: '16Uiu2HAkzn4wcaftAcsybKsE3GEboZCYLb7mpRBmPshpiwazAW3m',
    },
    {
      stats: {
        version_string: '',
        startOfCurrentUTCDay_string: '0001-01-01T00:00:00Z',
        rendezvous_string: '',
        pubSubTopic_string: '',
        numPinnedOrders_number: 0,
        numPeers_number: 0,
        numOrders_number: 0,
        numOrdersIncludingRemoved_number: 0,
        myPeerID: '',
        msg: '',
        maxExpirationTime_string: '',
        level: '',
        latestBlock_rpc_LatestBlock: {
          hash: '',
          number: 0,
        },
        ethereumChainID_number: 0,
        ethRPCRequestsSentInCurrentUTCDay_number: 0,
        ethRPCRateLimitExpiredRequests_number: 0,
        '@timestamp': '0001-01-01T00:00:00Z',
      },
      peers: null,
      meshVersion: '',
      ip: '',
      multiAddress: '/ip4/13.232.193.142/tcp/54804',
      peerId: 'Qmco58vrYfCDRPhRYkfZeomDwGTS2BCzcMsaYHfmivK9EX',
      name: 'Qmco58vrYfCDRPhRYkfZeomDwGTS2BCzcMsaYHfmivK9EX',
    },
    {
      stats: {
        version_string: '',
        startOfCurrentUTCDay_string: '0001-01-01T00:00:00Z',
        rendezvous_string: '',
        pubSubTopic_string: '',
        numPinnedOrders_number: 0,
        numPeers_number: 0,
        numOrders_number: 0,
        numOrdersIncludingRemoved_number: 0,
        myPeerID: '',
        msg: '',
        maxExpirationTime_string: '',
        level: '',
        latestBlock_rpc_LatestBlock: {
          hash: '',
          number: 0,
        },
        ethereumChainID_number: 0,
        ethRPCRequestsSentInCurrentUTCDay_number: 0,
        ethRPCRateLimitExpiredRequests_number: 0,
        '@timestamp': '0001-01-01T00:00:00Z',
      },
      peers: null,
      meshVersion: '',
      ip: '',
      multiAddress: '/ip4/85.10.126.142/tcp/51757',
      peerId: '16Uiu2HAkuhgfX5fss3dckd2sBatcLw5c7Sr6rDpxohBxkCwcDz2H',
      name: '16Uiu2HAkuhgfX5fss3dckd2sBatcLw5c7Sr6rDpxohBxkCwcDz2H',
    },
    {
      stats: {
        version_string: '',
        startOfCurrentUTCDay_string: '0001-01-01T00:00:00Z',
        rendezvous_string: '',
        pubSubTopic_string: '',
        numPinnedOrders_number: 0,
        numPeers_number: 0,
        numOrders_number: 0,
        numOrdersIncludingRemoved_number: 0,
        myPeerID: '',
        msg: '',
        maxExpirationTime_string: '',
        level: '',
        latestBlock_rpc_LatestBlock: {
          hash: '',
          number: 0,
        },
        ethereumChainID_number: 0,
        ethRPCRequestsSentInCurrentUTCDay_number: 0,
        ethRPCRateLimitExpiredRequests_number: 0,
        '@timestamp': '0001-01-01T00:00:00Z',
      },
      peers: null,
      meshVersion: '',
      ip: '',
      multiAddress: '/ip4/3.84.231.119/tcp/49918/ws',
      peerId: '16Uiu2HAkufBfZtuFAt9gQxqRxUnZktbbPoQ66duzFSf8jsofMBS9',
      name: '16Uiu2HAkufBfZtuFAt9gQxqRxUnZktbbPoQ66duzFSf8jsofMBS9',
    },
    {
      stats: {
        version_string: '7.1.1-beta-0xv3',
        startOfCurrentUTCDay_string: '2019-12-04T00:00:00Z',
        rendezvous_string: '/0x-mesh/network/1/version/2',
        pubSubTopic_string: '/0x-orders/network/1/version/2',
        numPinnedOrders_number: 0,
        numPeers_number: 64,
        numOrders_number: 85,
        numOrdersIncludingRemoved_number: 229,
        myPeerID: '16Uiu2HAm3eFZurNR65TESUayMCt5E2zrSD2Jypjs78Lea6GQ88oD',
        msg: 'current stats',
        maxExpirationTime_string: '115792089237316195423570985008687907853269984665640564039457584007913129639935',
        level: 'info',
        latestBlock_rpc_LatestBlock: {
          hash: '0x633a802df02ea711c3ed0dd5894215c18b7d08d171b1e8ebbb2bfca83cab16bf',
          number: 9051941,
        },
        ethereumChainID_number: 1,
        ethRPCRequestsSentInCurrentUTCDay_number: 28249,
        ethRPCRateLimitExpiredRequests_number: 0,
        '@timestamp': '2019-12-04T23:47:03Z',
      },
      peers: null,
      meshVersion: '',
      ip: '',
      multiAddress: '/ip4/54.236.76.96/tcp/60558',
      peerId: '16Uiu2HAm3eFZurNR65TESUayMCt5E2zrSD2Jypjs78Lea6GQ88oD',
      name: '16Uiu2HAm3eFZurNR65TESUayMCt5E2zrSD2Jypjs78Lea6GQ88oD',
    },
    {
      stats: {
        version_string: '',
        startOfCurrentUTCDay_string: '0001-01-01T00:00:00Z',
        rendezvous_string: '',
        pubSubTopic_string: '',
        numPinnedOrders_number: 0,
        numPeers_number: 0,
        numOrders_number: 0,
        numOrdersIncludingRemoved_number: 0,
        myPeerID: '',
        msg: '',
        maxExpirationTime_string: '',
        level: '',
        latestBlock_rpc_LatestBlock: {
          hash: '',
          number: 0,
        },
        ethereumChainID_number: 0,
        ethRPCRequestsSentInCurrentUTCDay_number: 0,
        ethRPCRateLimitExpiredRequests_number: 0,
        '@timestamp': '0001-01-01T00:00:00Z',
      },
      peers: null,
      meshVersion: '',
      ip: '',
      multiAddress: '/ip4/34.255.136.82/tcp/1024',
      peerId: '16Uiu2HAkybMwPLQxVTd7xRXPBX4xW344FELNCPVqxSd6AcmWKtxd',
      name: '16Uiu2HAkybMwPLQxVTd7xRXPBX4xW344FELNCPVqxSd6AcmWKtxd',
    },
    {
      stats: {
        version_string: '',
        startOfCurrentUTCDay_string: '0001-01-01T00:00:00Z',
        rendezvous_string: '',
        pubSubTopic_string: '',
        numPinnedOrders_number: 0,
        numPeers_number: 0,
        numOrders_number: 0,
        numOrdersIncludingRemoved_number: 0,
        myPeerID: '',
        msg: '',
        maxExpirationTime_string: '',
        level: '',
        latestBlock_rpc_LatestBlock: {
          hash: '',
          number: 0,
        },
        ethereumChainID_number: 0,
        ethRPCRequestsSentInCurrentUTCDay_number: 0,
        ethRPCRateLimitExpiredRequests_number: 0,
        '@timestamp': '0001-01-01T00:00:00Z',
      },
      peers: null,
      meshVersion: '',
      ip: '',
      multiAddress: '/ip4/54.89.174.211/tcp/45182',
      peerId: '16Uiu2HAkyTP77B769gy4qcmtoHUQHQWZb3oLCMyCvjWBjzFtLEVN',
      name: '16Uiu2HAkyTP77B769gy4qcmtoHUQHQWZb3oLCMyCvjWBjzFtLEVN',
    },
    {
      stats: {
        version_string: '',
        startOfCurrentUTCDay_string: '0001-01-01T00:00:00Z',
        rendezvous_string: '',
        pubSubTopic_string: '',
        numPinnedOrders_number: 0,
        numPeers_number: 0,
        numOrders_number: 0,
        numOrdersIncludingRemoved_number: 0,
        myPeerID: '',
        msg: '',
        maxExpirationTime_string: '',
        level: '',
        latestBlock_rpc_LatestBlock: {
          hash: '',
          number: 0,
        },
        ethereumChainID_number: 0,
        ethRPCRequestsSentInCurrentUTCDay_number: 0,
        ethRPCRateLimitExpiredRequests_number: 0,
        '@timestamp': '0001-01-01T00:00:00Z',
      },
      peers: null,
      meshVersion: '',
      ip: '',
      multiAddress: '/ip4/73.70.162.200/tcp/59530',
      peerId: '16Uiu2HAm8LTUCkhJXcLdpve7GmNyBbofAoKCkTMre5mCXaAeXJgE',
      name: '16Uiu2HAm8LTUCkhJXcLdpve7GmNyBbofAoKCkTMre5mCXaAeXJgE',
    },
    {
      stats: {
        version_string: '',
        startOfCurrentUTCDay_string: '0001-01-01T00:00:00Z',
        rendezvous_string: '',
        pubSubTopic_string: '',
        numPinnedOrders_number: 0,
        numPeers_number: 0,
        numOrders_number: 0,
        numOrdersIncludingRemoved_number: 0,
        myPeerID: '',
        msg: '',
        maxExpirationTime_string: '',
        level: '',
        latestBlock_rpc_LatestBlock: {
          hash: '',
          number: 0,
        },
        ethereumChainID_number: 0,
        ethRPCRequestsSentInCurrentUTCDay_number: 0,
        ethRPCRateLimitExpiredRequests_number: 0,
        '@timestamp': '0001-01-01T00:00:00Z',
      },
      peers: null,
      meshVersion: '',
      ip: '',
      multiAddress: '/ip4/73.70.162.200/tcp/60558',
      peerId: '16Uiu2HAm3UY1KQKBCitMW8BiGwQA1ZfX7AyibNxQ9UFebVDsLgYG',
      name: '16Uiu2HAm3UY1KQKBCitMW8BiGwQA1ZfX7AyibNxQ9UFebVDsLgYG',
    },
    {
      stats: {
        version_string: '',
        startOfCurrentUTCDay_string: '0001-01-01T00:00:00Z',
        rendezvous_string: '',
        pubSubTopic_string: '',
        numPinnedOrders_number: 0,
        numPeers_number: 0,
        numOrders_number: 0,
        numOrdersIncludingRemoved_number: 0,
        myPeerID: '',
        msg: '',
        maxExpirationTime_string: '',
        level: '',
        latestBlock_rpc_LatestBlock: {
          hash: '',
          number: 0,
        },
        ethereumChainID_number: 0,
        ethRPCRequestsSentInCurrentUTCDay_number: 0,
        ethRPCRateLimitExpiredRequests_number: 0,
        '@timestamp': '0001-01-01T00:00:00Z',
      },
      peers: null,
      meshVersion: '',
      ip: '',
      multiAddress: '/ip4/18.204.221.103/tcp/39074',
      peerId: 'QmZ2fbgXm1nfpNwNnv21WH7ZcAHG2caSFt9SSWJRRR1Rdr',
      name: 'QmZ2fbgXm1nfpNwNnv21WH7ZcAHG2caSFt9SSWJRRR1Rdr',
    },
    {
      stats: {
        version_string: '',
        startOfCurrentUTCDay_string: '0001-01-01T00:00:00Z',
        rendezvous_string: '',
        pubSubTopic_string: '',
        numPinnedOrders_number: 0,
        numPeers_number: 0,
        numOrders_number: 0,
        numOrdersIncludingRemoved_number: 0,
        myPeerID: '',
        msg: '',
        maxExpirationTime_string: '',
        level: '',
        latestBlock_rpc_LatestBlock: {
          hash: '',
          number: 0,
        },
        ethereumChainID_number: 0,
        ethRPCRequestsSentInCurrentUTCDay_number: 0,
        ethRPCRateLimitExpiredRequests_number: 0,
        '@timestamp': '0001-01-01T00:00:00Z',
      },
      peers: null,
      meshVersion: '',
      ip: '',
      multiAddress: '/ip4/92.251.59.182/tcp/60558',
      peerId: '16Uiu2HAmKZgtPmYm7ckEzFKdWmmhocVkTT7rDuBMv4YkMdVQY7ej',
      name: '16Uiu2HAmKZgtPmYm7ckEzFKdWmmhocVkTT7rDuBMv4YkMdVQY7ej',
    },
    {
      stats: {
        version_string: '',
        startOfCurrentUTCDay_string: '0001-01-01T00:00:00Z',
        rendezvous_string: '',
        pubSubTopic_string: '',
        numPinnedOrders_number: 0,
        numPeers_number: 0,
        numOrders_number: 0,
        numOrdersIncludingRemoved_number: 0,
        myPeerID: '',
        msg: '',
        maxExpirationTime_string: '',
        level: '',
        latestBlock_rpc_LatestBlock: {
          hash: '',
          number: 0,
        },
        ethereumChainID_number: 0,
        ethRPCRequestsSentInCurrentUTCDay_number: 0,
        ethRPCRateLimitExpiredRequests_number: 0,
        '@timestamp': '0001-01-01T00:00:00Z',
      },
      peers: null,
      meshVersion: '',
      ip: '',
      multiAddress: '/ip4/92.251.59.182/tcp/60558',
      peerId: '16Uiu2HAmHcKuknAq3tjj5UPqLnBsUrBZAVryXLYby1sojGwSktxK',
      name: '16Uiu2HAmHcKuknAq3tjj5UPqLnBsUrBZAVryXLYby1sojGwSktxK',
    },
    {
      stats: {
        version_string: '',
        startOfCurrentUTCDay_string: '0001-01-01T00:00:00Z',
        rendezvous_string: '',
        pubSubTopic_string: '',
        numPinnedOrders_number: 0,
        numPeers_number: 0,
        numOrders_number: 0,
        numOrdersIncludingRemoved_number: 0,
        myPeerID: '',
        msg: '',
        maxExpirationTime_string: '',
        level: '',
        latestBlock_rpc_LatestBlock: {
          hash: '',
          number: 0,
        },
        ethereumChainID_number: 0,
        ethRPCRequestsSentInCurrentUTCDay_number: 0,
        ethRPCRateLimitExpiredRequests_number: 0,
        '@timestamp': '0001-01-01T00:00:00Z',
      },
      peers: null,
      meshVersion: '',
      ip: '',
      multiAddress: '/ip4/73.70.162.200/tcp/60558',
      peerId: '16Uiu2HAmC5tT6kDT3FcQ9gg8AQZ3HvADkWsUnfLbNmVNwFfpskiH',
      name: '16Uiu2HAmC5tT6kDT3FcQ9gg8AQZ3HvADkWsUnfLbNmVNwFfpskiH',
    },
    {
      stats: {
        version_string: '',
        startOfCurrentUTCDay_string: '0001-01-01T00:00:00Z',
        rendezvous_string: '',
        pubSubTopic_string: '',
        numPinnedOrders_number: 0,
        numPeers_number: 0,
        numOrders_number: 0,
        numOrdersIncludingRemoved_number: 0,
        myPeerID: '',
        msg: '',
        maxExpirationTime_string: '',
        level: '',
        latestBlock_rpc_LatestBlock: {
          hash: '',
          number: 0,
        },
        ethereumChainID_number: 0,
        ethRPCRequestsSentInCurrentUTCDay_number: 0,
        ethRPCRateLimitExpiredRequests_number: 0,
        '@timestamp': '0001-01-01T00:00:00Z',
      },
      peers: null,
      meshVersion: '',
      ip: '',
      multiAddress: '/ip4/97.122.245.179/tcp/60558',
      peerId: '16Uiu2HAmHxFAMZEBUfYncWTa7iiFYs3Qk3YoGHHd8xpjJHGy6HTr',
      name: '16Uiu2HAmHxFAMZEBUfYncWTa7iiFYs3Qk3YoGHHd8xpjJHGy6HTr',
    },
    {
      stats: {
        version_string: '',
        startOfCurrentUTCDay_string: '0001-01-01T00:00:00Z',
        rendezvous_string: '',
        pubSubTopic_string: '',
        numPinnedOrders_number: 0,
        numPeers_number: 0,
        numOrders_number: 0,
        numOrdersIncludingRemoved_number: 0,
        myPeerID: '',
        msg: '',
        maxExpirationTime_string: '',
        level: '',
        latestBlock_rpc_LatestBlock: {
          hash: '',
          number: 0,
        },
        ethereumChainID_number: 0,
        ethRPCRequestsSentInCurrentUTCDay_number: 0,
        ethRPCRateLimitExpiredRequests_number: 0,
        '@timestamp': '0001-01-01T00:00:00Z',
      },
      peers: null,
      meshVersion: '',
      ip: '',
      multiAddress: '/ip4/3.89.153.176/tcp/60558',
      peerId: '16Uiu2HAmQudnXZrzT3ohubRxcF7CoReS6xDqZRRarsRG7EHKT7G1',
      name: '16Uiu2HAmQudnXZrzT3ohubRxcF7CoReS6xDqZRRarsRG7EHKT7G1',
    },
    {
      stats: {
        version_string: '',
        startOfCurrentUTCDay_string: '0001-01-01T00:00:00Z',
        rendezvous_string: '',
        pubSubTopic_string: '',
        numPinnedOrders_number: 0,
        numPeers_number: 0,
        numOrders_number: 0,
        numOrdersIncludingRemoved_number: 0,
        myPeerID: '',
        msg: '',
        maxExpirationTime_string: '',
        level: '',
        latestBlock_rpc_LatestBlock: {
          hash: '',
          number: 0,
        },
        ethereumChainID_number: 0,
        ethRPCRequestsSentInCurrentUTCDay_number: 0,
        ethRPCRateLimitExpiredRequests_number: 0,
        '@timestamp': '0001-01-01T00:00:00Z',
      },
      peers: null,
      meshVersion: '',
      ip: '',
      multiAddress: '/ip4/3.86.63.183/tcp/60558',
      peerId: '16Uiu2HAmGEtkyfCSt2GdnQsMf7h6H7SoXbzKsk8DABJyaBjcTst2',
      name: '16Uiu2HAmGEtkyfCSt2GdnQsMf7h6H7SoXbzKsk8DABJyaBjcTst2',
    },
    {
      stats: {
        version_string: '',
        startOfCurrentUTCDay_string: '0001-01-01T00:00:00Z',
        rendezvous_string: '',
        pubSubTopic_string: '',
        numPinnedOrders_number: 0,
        numPeers_number: 0,
        numOrders_number: 0,
        numOrdersIncludingRemoved_number: 0,
        myPeerID: '',
        msg: '',
        maxExpirationTime_string: '',
        level: '',
        latestBlock_rpc_LatestBlock: {
          hash: '',
          number: 0,
        },
        ethereumChainID_number: 0,
        ethRPCRequestsSentInCurrentUTCDay_number: 0,
        ethRPCRateLimitExpiredRequests_number: 0,
        '@timestamp': '0001-01-01T00:00:00Z',
      },
      peers: null,
      meshVersion: '',
      ip: '',
      multiAddress: '/ip4/73.70.162.200/tcp/60863',
      peerId: '16Uiu2HAkwF8uoxCeiQ3Lpba49z68uC8K9o5h9hCE6owMPnTt3cig',
      name: '16Uiu2HAkwF8uoxCeiQ3Lpba49z68uC8K9o5h9hCE6owMPnTt3cig',
    },
    {
      stats: {
        version_string: '',
        startOfCurrentUTCDay_string: '0001-01-01T00:00:00Z',
        rendezvous_string: '',
        pubSubTopic_string: '',
        numPinnedOrders_number: 0,
        numPeers_number: 0,
        numOrders_number: 0,
        numOrdersIncludingRemoved_number: 0,
        myPeerID: '',
        msg: '',
        maxExpirationTime_string: '',
        level: '',
        latestBlock_rpc_LatestBlock: {
          hash: '',
          number: 0,
        },
        ethereumChainID_number: 0,
        ethRPCRequestsSentInCurrentUTCDay_number: 0,
        ethRPCRateLimitExpiredRequests_number: 0,
        '@timestamp': '0001-01-01T00:00:00Z',
      },
      peers: null,
      meshVersion: '',
      ip: '',
      multiAddress: '/ip4/92.251.59.182/tcp/60558',
      peerId: '16Uiu2HAm5qMAagTbazjerLjMPsK78U3Zu6sZJ7JKVDeLiQysoBF7',
      name: '16Uiu2HAm5qMAagTbazjerLjMPsK78U3Zu6sZJ7JKVDeLiQysoBF7',
    },
    {
      stats: {
        version_string: '',
        startOfCurrentUTCDay_string: '0001-01-01T00:00:00Z',
        rendezvous_string: '',
        pubSubTopic_string: '',
        numPinnedOrders_number: 0,
        numPeers_number: 0,
        numOrders_number: 0,
        numOrdersIncludingRemoved_number: 0,
        myPeerID: '',
        msg: '',
        maxExpirationTime_string: '',
        level: '',
        latestBlock_rpc_LatestBlock: {
          hash: '',
          number: 0,
        },
        ethereumChainID_number: 0,
        ethRPCRequestsSentInCurrentUTCDay_number: 0,
        ethRPCRateLimitExpiredRequests_number: 0,
        '@timestamp': '0001-01-01T00:00:00Z',
      },
      peers: null,
      meshVersion: '',
      ip: '',
      multiAddress: '/ip4/159.65.4.82/tcp/49764',
      peerId: 'QmXkygYvb8JSJvcCtcVVZDucsqkgsuqsUx31JxPBuHA3vB',
      name: 'QmXkygYvb8JSJvcCtcVVZDucsqkgsuqsUx31JxPBuHA3vB',
    },
    {
      stats: {
        version_string: '',
        startOfCurrentUTCDay_string: '0001-01-01T00:00:00Z',
        rendezvous_string: '',
        pubSubTopic_string: '',
        numPinnedOrders_number: 0,
        numPeers_number: 0,
        numOrders_number: 0,
        numOrdersIncludingRemoved_number: 0,
        myPeerID: '',
        msg: '',
        maxExpirationTime_string: '',
        level: '',
        latestBlock_rpc_LatestBlock: {
          hash: '',
          number: 0,
        },
        ethereumChainID_number: 0,
        ethRPCRequestsSentInCurrentUTCDay_number: 0,
        ethRPCRateLimitExpiredRequests_number: 0,
        '@timestamp': '0001-01-01T00:00:00Z',
      },
      peers: null,
      meshVersion: '',
      ip: '',
      multiAddress: '/ip4/73.70.162.200/tcp/60558',
      peerId: '16Uiu2HAmUNXCDZnwXuz8WA5x9bPntfXdjJheSa4mN6DCTFcVRAbv',
      name: '16Uiu2HAmUNXCDZnwXuz8WA5x9bPntfXdjJheSa4mN6DCTFcVRAbv',
    },
    {
      stats: {
        version_string: '',
        startOfCurrentUTCDay_string: '0001-01-01T00:00:00Z',
        rendezvous_string: '',
        pubSubTopic_string: '',
        numPinnedOrders_number: 0,
        numPeers_number: 0,
        numOrders_number: 0,
        numOrdersIncludingRemoved_number: 0,
        myPeerID: '',
        msg: '',
        maxExpirationTime_string: '',
        level: '',
        latestBlock_rpc_LatestBlock: {
          hash: '',
          number: 0,
        },
        ethereumChainID_number: 0,
        ethRPCRequestsSentInCurrentUTCDay_number: 0,
        ethRPCRateLimitExpiredRequests_number: 0,
        '@timestamp': '0001-01-01T00:00:00Z',
      },
      peers: null,
      meshVersion: '',
      ip: '',
      multiAddress: '/ip4/18.188.189.248/tcp/55942/ws',
      peerId: '16Uiu2HAkyATn9MN9YD3wa86PDot1kJb4n4QtkyEDUqMyyddQgoQ3',
      name: '16Uiu2HAkyATn9MN9YD3wa86PDot1kJb4n4QtkyEDUqMyyddQgoQ3',
    },
    {
      stats: {
        version_string: '',
        startOfCurrentUTCDay_string: '0001-01-01T00:00:00Z',
        rendezvous_string: '',
        pubSubTopic_string: '',
        numPinnedOrders_number: 0,
        numPeers_number: 0,
        numOrders_number: 0,
        numOrdersIncludingRemoved_number: 0,
        myPeerID: '',
        msg: '',
        maxExpirationTime_string: '',
        level: '',
        latestBlock_rpc_LatestBlock: {
          hash: '',
          number: 0,
        },
        ethereumChainID_number: 0,
        ethRPCRequestsSentInCurrentUTCDay_number: 0,
        ethRPCRateLimitExpiredRequests_number: 0,
        '@timestamp': '0001-01-01T00:00:00Z',
      },
      peers: null,
      meshVersion: '',
      ip: '',
      multiAddress: '/ip4/164.132.227.24/tcp/60558',
      peerId: '16Uiu2HAkzt2sbVog9MWL9wDQm6LeLnoxthzcVdKavkxRVnRivCFZ',
      name: '16Uiu2HAkzt2sbVog9MWL9wDQm6LeLnoxthzcVdKavkxRVnRivCFZ',
    },
    {
      stats: {
        version_string: '',
        startOfCurrentUTCDay_string: '0001-01-01T00:00:00Z',
        rendezvous_string: '',
        pubSubTopic_string: '',
        numPinnedOrders_number: 0,
        numPeers_number: 0,
        numOrders_number: 0,
        numOrdersIncludingRemoved_number: 0,
        myPeerID: '',
        msg: '',
        maxExpirationTime_string: '',
        level: '',
        latestBlock_rpc_LatestBlock: {
          hash: '',
          number: 0,
        },
        ethereumChainID_number: 0,
        ethRPCRequestsSentInCurrentUTCDay_number: 0,
        ethRPCRateLimitExpiredRequests_number: 0,
        '@timestamp': '0001-01-01T00:00:00Z',
      },
      peers: null,
      meshVersion: '',
      ip: '',
      multiAddress: '/ip4/54.82.82.31/tcp/60558',
      peerId: '16Uiu2HAm6EfBg88xKnbiStTT6y6M2FWkUdreKajGQPAga9DXMCjh',
      name: '16Uiu2HAm6EfBg88xKnbiStTT6y6M2FWkUdreKajGQPAga9DXMCjh',
    },
    {
      stats: {
        version_string: '5.1.0-beta',
        startOfCurrentUTCDay_string: '0001-01-01T00:00:00Z',
        rendezvous_string: '/0x-mesh/network/3/version/1',
        pubSubTopic_string: '/0x-orders/network/3/version/1',
        numPinnedOrders_number: 0,
        numPeers_number: 58,
        numOrders_number: 72,
        numOrdersIncludingRemoved_number: 88203,
        myPeerID: '16Uiu2HAm1ir5aPhY3g4KHK8xKXnt2nT9VNzapX5eBjCCFE7GaWxB',
        msg: 'current stats',
        maxExpirationTime_string: '',
        level: 'info',
        latestBlock_rpc_LatestBlock: {
          hash: '0xcec7ed06ed98f802ad762c11690f3158f90686e6fc5ab270509a9ae0562e8d63',
          number: 6904877,
        },
        ethereumChainID_number: 0,
        ethRPCRequestsSentInCurrentUTCDay_number: 0,
        ethRPCRateLimitExpiredRequests_number: 0,
        '@timestamp': '2019-12-04T22:47:33Z',
      },
      peers: null,
      meshVersion: '',
      ip: '',
      multiAddress: '/ip4/167.71.14.6/tcp/60558',
      peerId: '16Uiu2HAm1ir5aPhY3g4KHK8xKXnt2nT9VNzapX5eBjCCFE7GaWxB',
      name: '16Uiu2HAm1ir5aPhY3g4KHK8xKXnt2nT9VNzapX5eBjCCFE7GaWxB',
    },
    {
      stats: {
        version_string: '',
        startOfCurrentUTCDay_string: '0001-01-01T00:00:00Z',
        rendezvous_string: '',
        pubSubTopic_string: '',
        numPinnedOrders_number: 0,
        numPeers_number: 0,
        numOrders_number: 0,
        numOrdersIncludingRemoved_number: 0,
        myPeerID: '',
        msg: '',
        maxExpirationTime_string: '',
        level: '',
        latestBlock_rpc_LatestBlock: {
          hash: '',
          number: 0,
        },
        ethereumChainID_number: 0,
        ethRPCRequestsSentInCurrentUTCDay_number: 0,
        ethRPCRateLimitExpiredRequests_number: 0,
        '@timestamp': '0001-01-01T00:00:00Z',
      },
      peers: null,
      meshVersion: '',
      ip: '',
      multiAddress: '/ip4/73.70.162.200/tcp/51165',
      peerId: '16Uiu2HAm7sTVkohtHT4VNK81k48iRCfzwY7y1aJ93GMCMpwVK46a',
      name: '16Uiu2HAm7sTVkohtHT4VNK81k48iRCfzwY7y1aJ93GMCMpwVK46a',
    },
    {
      stats: {
        version_string: '7.1.1-beta-0xv3',
        startOfCurrentUTCDay_string: '2019-12-04T00:00:00Z',
        rendezvous_string: '/0x-mesh/network/1/version/2',
        pubSubTopic_string: '/0x-orders/network/1/version/2',
        numPinnedOrders_number: 32,
        numPeers_number: 63,
        numOrders_number: 58,
        numOrdersIncludingRemoved_number: 282,
        myPeerID: '16Uiu2HAm2smCw7nMNRtMKX8M4VecEmJ74s7qaNzz4DJAvRkZ9RgX',
        msg: 'current stats',
        maxExpirationTime_string: '115792089237316195423570985008687907853269984665640564039457584007913129639935',
        level: 'info',
        latestBlock_rpc_LatestBlock: {
          hash: '0x635d24dec5f176cb0c7d2a656471866ea0f48a708a8f38a1f9b8c663c7290fd6',
          number: 9051615,
        },
        ethereumChainID_number: 1,
        ethRPCRequestsSentInCurrentUTCDay_number: 28710,
        ethRPCRateLimitExpiredRequests_number: 0,
        '@timestamp': '2019-12-04T22:24:22Z',
      },
      peers: null,
      meshVersion: '',
      ip: '',
      multiAddress: '/ip4/3.84.174.64/tcp/60558',
      peerId: '16Uiu2HAm2smCw7nMNRtMKX8M4VecEmJ74s7qaNzz4DJAvRkZ9RgX',
      name: '16Uiu2HAm2smCw7nMNRtMKX8M4VecEmJ74s7qaNzz4DJAvRkZ9RgX',
    },
  ],
};
